### PR TITLE
Add message reaction

### PR DESCRIPTION
**Pull request by Thegigadev**
- Added message reaction command (!react [message id] [emoji])
- Cleaned up README.md

### CODE REVIEW

**Comment by Thegigadev** [comment]
Hi Shell

**Comment by Thegigadev** [comment]
Working on new update that invalidates current code. New PR coming soon.

**Comment by Shell1010** [comment]
Just wanted to say you're ugly

**Comment by balluh** [comment]
W

**Comment by mishalhossin** [comment]
> Just wanted to say you're ugly

ask your mom

**Pull request closed without merging**
